apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: template-infra-app-namespace
  labels:
    app: template-infra-app
data:
  database.url: "jdbc:postgresql://postgres-service:5432/templatedb"
  app.name: "template-infra-app"
  log.level: "INFO"
