apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: template-infra-app-hpa
  namespace: template-infra-app-namespace
  labels:
    app: template-infra-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: template-infra-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
