apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: template-infra-app-ingress
  namespace: template-infra-app-namespace
  labels:
    app: template-infra-app
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  rules:
  - host: template-app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: template-infra-app-service
            port:
              number: 80
