apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: template-infra-app-namespace
  labels:
    app: template-infra-app
type: Opaque
stringData:
  database.username: "appuser"
  database.password: "changeme"
