name: Feature Branch Quality Checks

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - 'feature/**'

env:
  JAVA_VERSION: '17'

jobs:
  quality-checks:
    uses: a5x-reusable-workflows/.github/workflows/feature-java.yml@main
    with:
      java-version: ${{ env.JAVA_VERSION }}
    secrets: inherit
